### ISSUE TITLE
Drew and Ryan Quick Notes on Remaining Work

### ISSUE THREAD

**Issue by ryan-endacott** [EaseApp/web-backend#35]
## Application endpoints and data storage notes.  

Example application table:
```json
{
  "name": "users",
  "data": {
    "alice": {
      "age": 19
    }
  }
}
{
  "name": "dogs",
  "data": {
    "collies": {
      "olive": {
        "age": 1
      }
    }
  }
}
```

Example API calls:

All calls are given using a path like `"users.alice"`. 
The first component of the path will refer to a document in the RethinkDB application table.  Users won't need to know this, they'll only deal with data paths.   
```
read('dogs.collies') // read data
save('dogs.collies', data) // create or update
save('dogs.collies', null) // delete query
```

Docs on RethinkDB nested queries: http://rethinkdb.com/blog/1.8-release/

## Sync server notes

We're going to make a separate service in the same repo that listens to RethinkDB changefeeds.  It will accept socket connections and create a hash table from username/application => lists of the open socket connections.  Then the changes from the changefeed will be pushed to the connections in background goroutines.

**Comment by DrewWeth** [comment]
When it comes to querying an application. The logic in QueryApplicationHandler function queries an application by matching objects.
https://github.com/EaseApp/web-backend/blob/ADDING-AUTH/src/app/controllers/application/application.go

**Comment by ryan-endacott** [comment]
Sounds good, I'll use that.  

Also I forgot to mention in this issue:
@DrewWeth is going to be implementing the sync server, and I'll be implementing the remaining application endpoints.

**Comment by ryan-endacott** [comment]
DONE.
