### ISSUE TITLE
GitHub labeling standard.

### ISSUE THREAD

**Issue by ryan-endacott** [EaseApp/web-backend#4]
@Felttrip brought up that we should have a GitHub labeling standard for issues/pull requests.  What did you have in mind?

**Comment by Felttrip** [comment]
I was thinking like having in progress, ready for review,  and reviewed

**Comment by ryan-endacott** [comment]
Ohhh gotcha. I didn't quite get what you meant at first. I like that. I'll add them when on my computer.

**Comment by ryan-endacott** [comment]
I added:
- `looks good to me`, for when the reviewer has accepted the PR (should maybe call this one accepted?  Thoughts?)
- `needs more work`, for when the PR has to be updated before being accepted.
- `in progress`, for when the PR is still being worked on.  
- `needs review`, for when the PR is ready for review.  

Thoughts everyone?  
@EaseApp/hackers

**Comment by Felttrip** [comment]
I like it, it's casual

**Comment by ryan-endacott** [comment]
Cool, sounds good :+1:

**Comment by Felttrip** [comment]
I added the same ones to the web-front end for consistency.

**Comment by karrde00** [comment]
Thanks
