### ISSUE TITLE
Go dependency management.

### ISSUE THREAD

**Issue by ryan-endacott** [EaseApp/web-backend#9]
After looking into Go dependency management, I'm thinking we should use [godep](https://github.com/tools/godep).  It allows for reproducible builds by fixing dependencies.  It's similar to a package.json for npm.

It looks like Go will be officially moving to a similar solution sometime soon, and it's also how Google does their Go dependency management: https://groups.google.com/d/msg/golang-dev/nMWoEAG55v8/iJGgur7W_SEJ

What do you guys think?  @EaseApp/hackers.  Specifically @DrewWeth, @karrde00, and @Felttrip.

**Comment by Felttrip** [comment]
I was actually going to ask about using a dep manager. If godep looks good
we should go for it

**Comment by ryan-endacott** [comment]
Cool! Yeah it looks pretty nice.

**Comment by ryan-endacott** [comment]
Gonna go for it.  PR incoming soon.
